// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl9bDAJTPDtzhEspXera41Jxm4gg1lmKM',
    appId: '1:993011491957:web:ca1e4ae0e7cc3d3f57c43c',
    messagingSenderId: '993011491957',
    projectId: 'game-rk123',
    authDomain: 'game-rk123.firebaseapp.com',
    storageBucket: 'game-rk123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxU2qYZy8gnxsMSB1rplpiX_C3KBGy9EM',
    appId: '1:993011491957:android:b260e8fc9504809957c43c',
    messagingSenderId: '993011491957',
    projectId: 'game-rk123',
    storageBucket: 'game-rk123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpOj25hfzoab-Yc9v0hCWL0IyIA1Fiuvk',
    appId: '1:993011491957:ios:3fd3a783618f169757c43c',
    messagingSenderId: '993011491957',
    projectId: 'game-rk123',
    storageBucket: 'game-rk123.firebasestorage.app',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpOj25hfzoab-Yc9v0hCWL0IyIA1Fiuvk',
    appId: '1:993011491957:ios:3fd3a783618f169757c43c',
    messagingSenderId: '993011491957',
    projectId: 'game-rk123',
    storageBucket: 'game-rk123.firebasestorage.app',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl9bDAJTPDtzhEspXera41Jxm4gg1lmKM',
    appId: '1:993011491957:web:824436dee51262dd57c43c',
    messagingSenderId: '993011491957',
    projectId: 'game-rk123',
    authDomain: 'game-rk123.firebaseapp.com',
    storageBucket: 'game-rk123.firebasestorage.app',
  );

}